Working template package for ROS2 plugins

diff --git a/template_package/carma_package b/template_package/carma_package
--- a/template_package/carma_package
+++ b/template_package/carma_package
@@ -5,7 +5,8 @@ set -e
 # This script is used to build a package for the CARMA platform.
 # The script will create a new folder in the parent folder with the name of the package.
 # After calling the script the new package should be immeadiatly buildable
-# Usage: ./carma_package <this template_package path> <package name> <path to new package parent folder>
+# Usage: ./carma_package <this template_package path> <package name> <path to new package parent folder> <optional plugin type>
+# <optional plugin type> should be one of strategic, tactical, or control. If unset, then not a plugin 
 
 if [[ -z $BASH_VERSION  ]]; then
     echo "Bash version could not be checked. Please run this script using bash"
@@ -19,7 +20,7 @@ fi
 
 
 if [[ "$#" -ne 3 ]]; then
-    echo "Incorrect inputs: Input must be of form <this template_package path> <package name> <path to new package parent folder>"
+    echo "Incorrect inputs: Input must be of form <this template_package path> <package name> <path to new package parent folder> <optional plugin type>. If set, <optional plugin type> should be one of strategic, tactical, or control. If unset, then not a plugin"
     exit 2
 fi
 
@@ -55,14 +56,18 @@ plugin_type=$4
 if [ "$plugin_type" = "strategic" ] || [ "$plugin_type" = "tactical" ] || [ "$plugin_type" = "control" ]; then
    
     echo "Making plugin of type: $plugin_type"
+
+    base_node_dep='<depend>carma_guidance_plugins<\/depend>'
     
 elif [[ -z ${plugin_type} ]]; then
 
-    echo "Plugin type not provided assuming standard node"
+    echo "Plugin type not provided assuming standard node (not a plugin)"
     plugin_type="none"
+    base_node_dep=''
 
 else
     echo "Plugin type not valid. Must be one of strategic, tactical, or control. If not making a plugin leave field empty" 
+    exit 2
 fi
 
 target_path=$(realpath ${package_parent_path}/${package_name})
@@ -79,91 +84,56 @@ if [[ $PWD != $(realpath ${target_path}) ]]; then
     exit 2
 fi
 
-plugin_base_overrides="bool get_availability() override;\
-\
-    std::string get_name() override;\
-\
-    std::string get_version_id() override;\
-\
-    std::string get_capability() override;\
-    \
-    /**\
-     * \brief This method should be used to load parameters and will be called no the configure state transition.\
-     */ \
-    carma_ros2_utils::CallbackReturn on_configure_plugin();\
-\
-    /**\
-     * TODO for USER: The following lifecycle overrides are also available if needed\
-     * on_activate_plugin\
-     * on_deactivate_plugin\
-     * on_cleanup_plugin\
-     * on_shutdown_plugin\
-     * on_error_plugin\
-     */\
-    "
-
+# Cleanup alternative node files based on user specified type befoe substitutions
 if [ "$plugin_type" = "strategic" ]; then
 
-base_node_overrides="void plan_maneuvers_callback(\
-      std::shared_ptr<rmw_request_id_t>, \
-      carma_planning_msgs::srv::PlanManeuvers::Request::SharedPtr, \
-      carma_planning_msgs::srv::PlanManeuvers::Response::SharedPtr) override;\
-\
-    $plugin_base_overrides
-    "
+    rm include/template_package/template_package_node.hpp
+    rm include/template_package/template_tactical_plugin_node.hpp
+    rm include/template_package/template_control_plugin_node.hpp
 
-base_node='carma_guidance_plugins::StrategicPlugin'
-base_node_header='#include <carma_guidance_plugins/strategic_plugin.hpp>'
+    rm src/template_package_node.cpp
+    rm src/template_tactical_plugin_node.cpp
+    rm src/template_control_plugin_node.cpp
 
 elif [ "$plugin_type" = "tactical" ]; then
 
-base_node_overrides="void plan_trajectory_callback(\
-      std::shared_ptr<rmw_request_id_t>, \
-      carma_planning_msgs::srv::PlanTrajectory::Request::SharedPtr, \
-      carma_planning_msgs::srv::PlanTrajectory::Response::SharedPtr) override;\
-\
-    $plugin_base_overrides
-    "
+    rm include/template_package/template_package_node.hpp
+    rm include/template_package/template_strategic_plugin_node.hpp
+    rm include/template_package/template_control_plugin_node.hpp
 
-base_node='carma_guidance_plugins::TacticalPlugin'
-base_node_header='#include <carma_guidance_plugins/tactical_plugin.hpp>'
+    rm src/template_package_node.cpp
+    rm src/template_strategic_plugin_node.cpp
+    rm src/template_control_plugin_node.cpp
 
 elif [ "$plugin_type" = "control" ]; then
 
-base_node_overrides="autoware_msgs::msg::ControlCommandStamped generate_command() override;\
-\
-    $plugin_base_overrides
-    "
+    rm include/template_package/template_package_node.hpp
+    rm include/template_package/template_strategic_plugin_node.hpp
+    rm include/template_package/template_tactical_plugin_node.hpp
 
-base_node='carma_guidance_plugins::ControlPlugin'
-base_node_header='#include <carma_guidance_plugins/control_plugin.hpp>'
+    rm src/template_package_node.cpp
+    rm src/template_strategic_plugin_node.cpp
+    rm src/template_tactical_plugin_node.cpp
 
 else
 
-### Non-Plugin Base Node Substitutions ###
-base_node_overrides='carma_ros2_utils::CallbackReturn handle_on_configure(const rclcpp_lifecycle::State \&prev_state);\
-\
-    /**\
-     * TODO for USER: The following lifecycle overrides are also available if needed\
-     * handle_on_activate\
-     * handle_on_deactivate\
-     * handle_on_cleanup\
-     * handle_on_shutdown\
-     * handle_on_error\
-     */\
-    '
+    rm include/template_package/template_strategic_plugin_node.hpp
+    rm include/template_package/template_tactical_plugin_node.hpp
+    rm include/template_package/template_control_plugin_node.hpp
 
-base_node='carma_ros2_utils::CarmaLifecycleNode'
-base_node_header='#include <carma_ros2_utils/carma_lifecycle_node.hpp>'
+    rm src/template_strategic_plugin_node.cpp
+    rm src/template_tactical_plugin_node.cpp
+    rm src/template_control_plugin_node.cpp
 
 fi
 
 # Perform substitutions
 find . -type f -exec sed -i "s/<SUB><package_name>/${package_name}/g" {} \;
 find . -type f -exec sed -i "s/<SUB><year>/${current_year}/g" {} \;
-find . -type f -exec sed -i "s|<SUB><base_node_overrides>|${base_node_overrides}|g" {} \;
-find . -type f -exec sed -i "s|<SUB><base_node_header>|${base_node_header}|g" {} \;
-find . -type f -exec sed -i "s|<SUB><base_node>|${base_node}|g" {} \;
+find . -type f -exec sed -i "s/<SUB><base_node_dep>/${base_node_dep}/g" {} \;
+#find . -type f -exec sed -i "s/<SUB><world_model_dep>/${world_model_dep}/g" {} \;
+#find . -type f -exec sed -i "s/<SUB><autonomy_lib_dep>/${autonomy_lib_dep}/g" {} \;
+
 
 # Update file names for new package
 shopt -s globstar
@@ -173,7 +143,14 @@ for f in ./**; do
         continue
     fi
 
+    # Here the files will be renamed. 
+    # Since the user must specify one of none, strategic, tactical, or control and we delete the conflicting files above
+    # We should be able to safely replace all the rules even when unused without conflict
     new_name=$(echo $f | sed "s/template_package/${package_name}/g")
+    new_name=$(echo $new_name | sed "s/template_strategic_plugin/${package_name}/g")
+    new_name=$(echo $new_name | sed "s/template_tactical_plugin/${package_name}/g")
+    new_name=$(echo $new_name | sed "s/template_control_plugin/${package_name}/g")
+
     directory_name=$(dirname $new_name)
     if [[ ! -d $directory_name ]]; then
         mkdir -p $directory_name
