Functional template_package

diff --git a/template_package/carma_package b/template_package/carma_package
--- a/template_package/carma_package
+++ b/template_package/carma_package
@@ -1,21 +1,34 @@
 #!/bin/bash
 
-if [ "$#" -ne 3 ]; then
+set -e
+
+if [[ -z $BASH_VERSION  ]]; then
+    echo "Bash version could not be checked. Please run this script using bash"
+    exit 2
+fi
+
+if [[ "${BASH_VERSION:0:1}" -lt 4 ]]; then
+    echo "Bash version 4 or higher is required.  Exiting."
+    exit 2
+fi
+
+
+if [[ "$#" -ne 3 ]]; then
     echo "Incorrect inputs: Input must be of form <this template_package path> <package name> <path to new package parent folder>"
     exit 2
 fi
 
-template_package_path = $1
+template_package_path=$1
 
-if [[ ! -d ${template_package_path} ]] then
+if [[ ! -d ${template_package_path} ]]; then
     echo "template_package directory ${template_package_path} DOES NOT exists." 
     exit 2
 fi
 
 
-package_name = $2
+package_name=$2
 
-if [[ -z ${package_name} ]] then
+if [[ -z ${package_name} ]]; then
     echo "Package name not provided." 
     exit 2
 fi
@@ -25,20 +38,64 @@ if [[ "${package_name}" =~ [^a-zA-Z0-9_\ ] ]]; then
   exit 2
 fi
 
-package_parent_path = $3
+package_parent_path=$3
 
-if [[ ! -d ${package_parent_path} ]] then
+if [[ ! -d ${package_parent_path} ]]; then
     echo "New package parent path directory ${package_parent_path} DOES NOT exists." 
     exit 2
 fi
 
-cp ${template_package_path} ${package_parent_path}/${package_name}
+target_path=$(realpath ${package_parent_path}/${package_name})
 
-cd ${package_parent_path}/${package_name}
+cp -r ${template_package_path} ${target_path}
 
-current_year = date +"%Y"
+cd ${target_path}
+
+current_year=$(date +"%Y")
+
+if [[ $PWD != $(realpath ${target_path}) ]]; then
+    echo "Failed to create target package directory. Check your path and permissions" 
+    exit 2
+fi
 
 find . -type f -exec sed -i "s/<SUB><package_name>/${package_name}/g" {} \;
 find . -type f -exec sed -i "s/<SUB><year>/${current_year}/g" {} \;
 
+shopt -s globstar
+for f in ./**; do
+
+    if [[ -d $f ]]; then
+        continue
+    fi
+
+    new_name=$(echo $f | sed "s/template_package/${package_name}/g")
+    directory_name=$(dirname $new_name)
+    if [[ ! -d $directory_name ]]; then
+        mkdir -p $directory_name
+    fi
+
+    if [[ $f != $new_name ]]; then
+        mv $f $new_name
+    fi
+done
+
+for d in ./**; do
+
+    if [[ -f $d ]]; then
+        continue
+    fi
+
+    if [[ "$d" == *"template_package"* ]]; then
+        rm -r $d
+    fi
+done
+
+
+rm CATKIN_IGNORE
+rm COLCON_IGNORE
+rm README.md
+rm carma_package
+mv ${package_name}_README.md README.md
+
+echo "${package_name} created at ${target_path}"
 
